export const ADDFAVORITE = "ADD";
export const DELETEFAVORITE = "DELETE";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const RESET = "RESET";
export const PAGIANTE = "paginate";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME"
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION"
export const ORDER_BY_DIFFICULTY = "ORDER_BY_DIFICULTY"
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const SET_CURRENT_PAGE="SET_CURRENT_PAGE"